# This workflow will build, test, sign and package a WPF or Windows Forms desktop application
# built on .NET Core.

name: WPF Desktop

on:
  push:
    branches: [ main ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest

    env:
      PROJECT_PATH: src\Parsec.WPF\Parsec.WPF.csproj

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Restore
      run: dotnet restore ${{ env.PROJECT_PATH }}

    - name: Build
      run: dotnet build ${{ env.PROJECT_PATH }} -c ${{ matrix.configuration }} --no-restore

    - name: Publish
      run: dotnet publish ${{ env.PROJECT_PATH }} -c ${{ matrix.configuration }} --no-build

    - name: Create Code Signing Certificate
      run: |
        New-Item -ItemType directory -Path certificate
        Set-Content -Path certificate\certificate.txt -Value '${{ secrets.CERTIFICATE }}'
        certutil -decode certificate\certificate.txt certificate\certificate.pfx

    - name: Code Sign 2021
        run: |
          & 'C:/Program Files (x86)/Windows Kits/10/bin/10.0.17763.0/x86/signtool.exe' sign /f certificate\certificate.pfx /p '${{ secrets.CERTIFICATE_PASS }}' /t http://timestamp.comodoca.com/authenticode src\Parsec.WPF\bin\Release\net5.0-windows\win-x64\publish\*.exe

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Artifacts
        path: src\Parsec.WPF\bin\Release\net5.0-windows\win-x64\publish\*.exe
