# This workflow will build, test, sign and package a WPF or Windows Forms desktop application
# built on .NET Core.

name: WPF Desktop

on:
  push:
    branches: [ main ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest

    env:
      PROJECT_PATH: src\Parsec.WPF\Parsec.WPF.csproj

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Restore
      run: dotnet restore ${{ env.PROJECT_PATH }}

    - name: Build
      run: dotnet build ${{ env.PROJECT_PATH }} -c ${{ matrix.configuration }} --no-restore

    - name: Publish
      run: dotnet publish ${{ env.PROJECT_PATH }} -c ${{ matrix.configuration }} --no-buildfiguration: ${{ matrix.configuration }}

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Artifacts
        path: ${{ env.PROJECT_PATH }}\bin\Release\net5.0-windows\win-x64\publish\*.exe
